### ISSUE TITLE
The uploaded images are all displayed with the same default one

### ISSUE THREAD

**Issue by eversatis** [OdooCommunityWidgets/website_multi_image#10] opened 2014-12-29 17:56 UTC
The uploaded images are all displayed with the same default one. No matter what image you are uploading, it will show the duplicated default images all the same.

Thanks for your time & Best regards

**Comment by lukebranch** [comment] 2014-12-30 00:02
@frankmiao2015 ,

Could you take a screenshot of the issue? I can't reproduce it on my odoo instance.

**Comment by eversatis** [comment] 2014-12-30 03:16
This only happens to the first products I test before. I tested another product and it works fine. I did clear all my local cookies. I think it may caused by the Odoo cache.  So I think this issue can be closed.

Thank you very much.

发自 Surface

发件人: Luke Branch
发送时间: ‎2014‎年‎12‎月‎30‎日, ‎星期二 ‎8‎:‎02
收件人: OdooCommunityWidgets/website_multi_image
抄送: Frank Miao

@frankmiao2015 ,

Could you take a screenshot of the issue? I can't reproduce it on my odoo instance.

**Comment by lukebranch** [comment] 2014-12-30 03:24
@frankmiao2015 ,

Thanks for letting me know. I think this may have something to do with your Nginx cache control headers. Does it happen if you access the odoo server ip directly rather than though the Nginx proxy? I have experienced a similar issue previously and found it to be caused by Nginx cache control headers.

I'll close this, however if you continue to have the problem and it is unrelated to nginx/odoo cache please feel free to re-open it.

**Closed as completed by lukebranch** 2014-12-30 03:24 UTC

**Comment by eversatis** [comment] 2014-12-30 04:20
I connect it without the Nginx, it is still the same. The Odoo cache is also kind of complex. I encountered similar problems when I use openerp 7.0. I am not a pro technichian so I can not tell exactly. Anyway, for now it is not matters at all. I really like it! Thanks!

发自 Surface

发件人: Luke Branch
发送时间: ‎2014‎年‎12‎月‎30‎日, ‎星期二 ‎11‎:‎24
收件人: OdooCommunityWidgets/website_multi_image
抄送: Frank Miao

@frankmiao2015 ,

Thanks for letting me know. I think this may have something to do with your Nginx cache control headers. Does it happen if you access the odoo server ip directly rather than though the Nginx proxy? I have experienced a similar issue previously and found it to be caused by Nginx cache control headers.

I'll close this, however if you continue to have the problem and it is unrelated to nginx/odoo cache please feel free to re-open it.

**Comment by lukebranch** [comment] 2014-12-30 05:58
@frankmiao2015 ,

Thanks for the feedback. If you have any feature requests, or notice any bugs please feel free to open an issue here and i'll work on integrating fixes/features as soon as I can.

**Comment by nggopakumar** [comment] 2015-03-25 14:26
The issue occurs when there are variants for the product, but for a product without any variant the added images are coming separately. But for a product with variants the uploaded images loaded are the same default one.

**Comment by lukebranch** [comment] 2015-03-28 01:51
@nggopakumar ,

Thanks for the feedback, would you mind providing steps to reproduce the error, or an GIF screencap using something like?:

http://www.cockos.com/licecap/

**Comment by nggopakumar** [comment] 2015-03-30 05:16
@lukebranch  
Add any variant to a product (for example take a jacket as a product and some variants based on sizes 'L','M',,'S','XL' etc) and add different images to the product. You can now see that all the images shown in the product website page is same. But if you delete the variants for the product, it will show all the images in the website product page which you have added to the product.

**Comment by lukebranch** [comment] 2015-03-30 07:11
@nggopakumar ,

Can you take a look at the product variants in the backend and make sure you can see different images stored on variants in the backend (ie. Sales >> Product Variants)?

Once I know this i'll try to reproduce this on a dev instance myself.

**Comment by nggopakumar** [comment] 2015-03-30 07:50
@lukebranch  Yes, I am able t see different images at product variants.

**Comment by lukebranch** [comment] 2015-03-30 09:14
@nggopakumar ,

I will try to reproduce this on my end soon. FYI - I plan to remove my python from this module to base the module on product_multi_image once it has been merged into the OCA branch for 8.0 here:

https://github.com/OCA/product-attribute/tree/8.0/__unported__/product_images

this should be merged within a couple of weeks and will handle the product images in a far better way than it does now. For this reason I would recommend holding off on any significant work involving this module until I have created another branch with product_multi_image (this is currently called product_images in OCA) as a base.

If there is a simple fix for the issue you're experiencing i'll merge it into the current 8.0 branch.

Could you provide me with details about your setup:

installation method (eg. apt-get install, sh script install, etc.), modules installed, and OS? This will help me to troubleshoot better if I cannot reproduce it in my instance.

**Comment by nggopakumar** [comment] 2015-03-30 10:06
@lukebranch  I am running the server as a service from terminal in ubuntu 14.04LTS and the modules installed are website_sale and website_multi_image.
